pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
  - name: Automatic merge renovate PRs
    conditions:
      - author=renovate[bot]
      - check-success=CI/CD
      - -conflict # No conflict
      - -draft # The PR should not be a 'draft'
    actions:
      merge:
        method: rebase
