version: '3'

services:
  component-1:
    build: .
    environment:
      NEIGHBOUR_HOST: "component-2"
    networks:
      - proxynet

  component-2:
    build: .
    environment:
      NEIGHBOUR_HOST: "component-1"
    networks:
      - proxynet

networks:
  proxynet:
      name: custom_network