name: CI/CD Pipeline

on:
  workflow_call:
  workflow_dispatch:

env:
  JDK_DISTRIUTION: temurin
  JDK_VERSION: 17.0.4

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: ${{ env.JDK_DISTRIUTION }}
          java-version: ${{ env.JDK_VERSION }}
          cache: gradle
      # TODO: complete with other steps

  release:
    concurrency:
      group: release
    needs: [build]
    runs-on: ubuntu-latest
    # Prevent the release job if the run is on a PR or a fork
    if: >-
      !github.event.repository.fork
      && (github.event_name != 'pull_request' ||
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: ${{ env.JDK_DISTRIUTION }}
          java-version: ${{ env.JDK_VERSION }}
          cache: gradle
      # TODO: complete with other steps

  success:
    runs-on: ubuntu-latest
    needs:
      - release
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}