name: CI/CD

on:
  push:
    branches-ignore:
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      - '.gitignore'
      - '.mergify.yml'
  pull_request:
  workflow_dispatch:

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
      || startsWith(github.head_ref, 'refs/heads/dependabot/')
    steps:
      - run: 'true'
  ci-cd:
    needs: [ dispatcher ]
    uses: ./.github/workflows/build-and-release.yml
    secrets: inherit
