name: Publish docsite

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.1.0
      - name: Build docsite
        run: |
          cd docsite
          npm install
          npm run build
      - name: Release docsite to Github Pages
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          BRANCH: gh-pages
          FOLDER: docsite/build
